# Generated by Django 5.2.4 on 2025-07-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mensajecontacto_remove_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=200),
        ),
    ]
