# Generated by Django 5.2.4 on 2025-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_mensajecontacto_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
