# Generated by Django 5.2.4 on 2025-07-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_producto_nombre_alter_usuario_celular_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
